### ISSUE TITLE
Synthetic preferences - no preferences received

### ISSUE THREAD

**Issue by JawwadF** [mrahtz/learning-from-human-preferences#2]
I tried to train using synthetic preferences in the MovingDot environment using the command:

> python3 run.py train_policy_with_preferences MovingDotNoFrameskip-v0 --synthetic_prefs --ent_coef 0.02 --million_timesteps 0.15

However, it doesn't appear to be learning, and I continuously get the output
> Waiting for preferences: 0 so far

Do you know what might be going on here?

(Also great job on this project!)

**Comment by JawwadF** [comment]
Also, I can confirm that training with the original reward function from the environment works fine.

Command used:
>python3 run.py train_policy_with_original_rewards MovingDotNoFrameskip-v0 --million_timesteps 0.25

**Comment by JawwadF** [comment]
It seems to be collecting synthetic preferences now! Thank you, I'll have to check whether it's learning - I'll get back to you to confirm.

Thanks for fixing the issue!

**Comment by mrahtz** [comment]
Assuming this is fixed.
